# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maininterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Program(object):
    def setupUi(self, Program):
        Program.setObjectName("Program")
        Program.resize(1600, 900)
        Program.setMaximumSize(QtCore.QSize(1600, 900))
        font = QtGui.QFont()
        font.setPointSize(9)
        Program.setFont(font)
        Program.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Program.setFocusPolicy(QtCore.Qt.ClickFocus)
        Program.setLayoutDirection(QtCore.Qt.LeftToRight)
        Program.setStyleSheet("QWidget#QWProgram{\n"
"background-color: rgb(248, 248, 242);\n"
"border-radius: 10px;\n"
"}\n"
"QLabel{\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(40, 42, 48);\n"
"}\n"
"QStackedWidget{\n"
"border-bottom-right-radius: 10px;\n"
"}\n"
"QFrame#QFMenu{\n"
"background-color: rgb(68, 71, 90);\n"
"border-right: 10px solid rgb(255, 184, 108);\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"}\n"
"QLabel#QLTitle{\n"
"background-color: rgb(98, 114, 164);\n"
"border-top-right-radius: 10px;\n"
"color: rgb(242, 242, 248);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"text-align: center;\n"
"}\n"
"QPushButton#QPBProduct, #QPBSell, #QPBStatistics, #QPBExit{\n"
"color: rgb(248, 248, 242);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"height: 60px;\n"
"width: 170px;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"text-align: left;\n"
"padding-left: 15px;\n"
"border-top-left-radius: 30px;\n"
"border-bottom-left-radius: 30px;\n"
"}\n"
"QPushButton#QPBProduct:hover, #QPBSell:hover, \n"
"#QPBStatistics:hover, #QPBExit:hover{\n"
"font: 13pt \"MS Shell Dlg 2\";\n"
"}\n"
"QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(68, 71, 90);\n"
"border-radius: 5px;\n"
"height: 30px;\n"
"color: rgb(40, 42, 54);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QTableWidget{\n"
"border: none;\n"
"background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QTableWidget::item{\n"
"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-bottom: 1px solid rgb(68, 71, 90);\n"
"border-left: 1px solid rgb(68, 71, 90);\n"
"color: rgb(40, 42, 48);\n"
"padding-left: 5px;\n"
"}\n"
"QTableWidget QHeaderView::section{\n"
"background-color: rgb(68, 71, 90);\n"
"border: none;\n"
"color: rgb(248, 248, 242);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"padding: 5px;\n"
"}\n"
"QTableWidget::item:selected {\n"
"background: rgba(40, 42, 54, 50);\n"
"}\n"
"QScrollBar:vertical {\n"
"border: 2px solid rgb(68, 71, 90);\n"
"background: rgb(98, 114, 164);\n"
"width: 10px;\n"
"margin: 42px 0 42px 0;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"background: white;\n"
"min-height: 20px;\n"
"border-radius: 3px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"border: 2px solid rgb(68, 71, 90);\n"
"background: rgb(98, 114, 164);\n"
"height: 40px;\n"
"subcontrol-position: bottom;\n"
"subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"border: 2px solid rgb(68, 71, 90);\n"
"background: rgb(98, 114, 164);\n"
"height: 40px;\n"
"subcontrol-position: top;\n"
"subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"background: none;\n"
"}")
        self.QWProgram = QtWidgets.QWidget(Program)
        self.QWProgram.setGeometry(QtCore.QRect(0, 0, 1600, 900))
        self.QWProgram.setObjectName("QWProgram")
        self.QFMenu = QtWidgets.QFrame(self.QWProgram)
        self.QFMenu.setGeometry(QtCore.QRect(0, 0, 250, 900))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.QFMenu.setFont(font)
        self.QFMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.QFMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.QFMenu.setLineWidth(0)
        self.QFMenu.setObjectName("QFMenu")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.QFMenu)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(59, 220, 201, 242))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.QVBLMenu = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.QVBLMenu.setContentsMargins(0, 0, 0, 0)
        self.QVBLMenu.setSpacing(0)
        self.QVBLMenu.setObjectName("QVBLMenu")
        self.QPBProduct = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.QPBProduct.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.QPBProduct.setAutoFillBackground(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon/product.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QPBProduct.setIcon(icon)
        self.QPBProduct.setIconSize(QtCore.QSize(20, 20))
        self.QPBProduct.setObjectName("QPBProduct")
        self.QVBLMenu.addWidget(self.QPBProduct)
        self.QPBSell = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.QPBSell.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.QPBSell.setAutoFillBackground(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icon/billing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QPBSell.setIcon(icon1)
        self.QPBSell.setIconSize(QtCore.QSize(20, 20))
        self.QPBSell.setObjectName("QPBSell")
        self.QVBLMenu.addWidget(self.QPBSell)
        self.QPBStatistics = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.QPBStatistics.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.QPBStatistics.setAutoFillBackground(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/icon/statistics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QPBStatistics.setIcon(icon2)
        self.QPBStatistics.setIconSize(QtCore.QSize(20, 20))
        self.QPBStatistics.setObjectName("QPBStatistics")
        self.QVBLMenu.addWidget(self.QPBStatistics)
        self.QPBExit = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.QPBExit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.QPBExit.setAutoFillBackground(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/icon/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QPBExit.setIcon(icon3)
        self.QPBExit.setIconSize(QtCore.QSize(20, 20))
        self.QPBExit.setObjectName("QPBExit")
        self.QVBLMenu.addWidget(self.QPBExit)
        self.QLTitle = QtWidgets.QLabel(self.QWProgram)
        self.QLTitle.setGeometry(QtCore.QRect(250, 0, 1350, 50))
        self.QLTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.QLTitle.setObjectName("QLTitle")
        self.QSW = QtWidgets.QStackedWidget(self.QWProgram)
        self.QSW.setGeometry(QtCore.QRect(250, 50, 1350, 850))
        self.QSW.setLineWidth(0)
        self.QSW.setMidLineWidth(0)
        self.QSW.setObjectName("QSW")
        self.QWProduct = QtWidgets.QWidget()
        self.QWProduct.setObjectName("QWProduct")
        self.QTWProduct = QtWidgets.QTableWidget(self.QWProduct)
        self.QTWProduct.setGeometry(QtCore.QRect(40, 100, 1271, 701))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.QTWProduct.setFont(font)
        self.QTWProduct.setMouseTracking(False)
        self.QTWProduct.setTabletTracking(False)
        self.QTWProduct.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.QTWProduct.setAcceptDrops(False)
        self.QTWProduct.setAutoFillBackground(False)
        self.QTWProduct.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.QTWProduct.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.QTWProduct.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.QTWProduct.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.QTWProduct.setDragEnabled(False)
        self.QTWProduct.setAlternatingRowColors(False)
        self.QTWProduct.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.QTWProduct.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.QTWProduct.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.QTWProduct.setShowGrid(False)
        self.QTWProduct.setGridStyle(QtCore.Qt.NoPen)
        self.QTWProduct.setObjectName("QTWProduct")
        self.QTWProduct.setColumnCount(8)
        self.QTWProduct.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.QTWProduct.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWProduct.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWProduct.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWProduct.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWProduct.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWProduct.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWProduct.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWProduct.setHorizontalHeaderItem(7, item)
        self.QTWProduct.horizontalHeader().setVisible(False)
        self.QTWProduct.horizontalHeader().setCascadingSectionResizes(True)
        self.QTWProduct.horizontalHeader().setDefaultSectionSize(100)
        self.QTWProduct.horizontalHeader().setHighlightSections(True)
        self.QTWProduct.horizontalHeader().setMinimumSectionSize(40)
        self.QTWProduct.horizontalHeader().setSortIndicatorShown(False)
        self.QTWProduct.horizontalHeader().setStretchLastSection(True)
        self.QTWProduct.verticalHeader().setVisible(False)
        self.QTWProduct.verticalHeader().setCascadingSectionResizes(False)
        self.QTWProduct.verticalHeader().setDefaultSectionSize(40)
        self.QTWProduct.verticalHeader().setHighlightSections(True)
        self.QTWProduct.verticalHeader().setMinimumSectionSize(40)
        self.QTWProduct.verticalHeader().setSortIndicatorShown(False)
        self.QTWProduct.verticalHeader().setStretchLastSection(False)
        self.QLESearchProduct = QtWidgets.QLineEdit(self.QWProduct)
        self.QLESearchProduct.setGeometry(QtCore.QRect(40, 40, 301, 40))
        self.QLESearchProduct.setMaximumSize(QtCore.QSize(400, 16777215))
        self.QLESearchProduct.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.QLESearchProduct.setStyleSheet("border-radius: 20px;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"")
        self.QLESearchProduct.setObjectName("QLESearchProduct")
        self.QPBAddProduct = QtWidgets.QPushButton(self.QWProduct)
        self.QPBAddProduct.setGeometry(QtCore.QRect(1150, 40, 161, 40))
        self.QPBAddProduct.setFocusPolicy(QtCore.Qt.TabFocus)
        self.QPBAddProduct.setStyleSheet("background-color: rgb(80, 250, 123);\n"
"height: 40px;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 20px;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/icon/addproduct.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QPBAddProduct.setIcon(icon4)
        self.QPBAddProduct.setIconSize(QtCore.QSize(25, 25))
        self.QPBAddProduct.setObjectName("QPBAddProduct")
        self.QSW.addWidget(self.QWProduct)
        self.QWSell = QtWidgets.QWidget()
        self.QWSell.setObjectName("QWSell")
        self.QTWProductToOrder = QtWidgets.QTableWidget(self.QWSell)
        self.QTWProductToOrder.setGeometry(QtCore.QRect(70, 150, 1211, 651))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.QTWProductToOrder.setFont(font)
        self.QTWProductToOrder.setMouseTracking(False)
        self.QTWProductToOrder.setTabletTracking(False)
        self.QTWProductToOrder.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.QTWProductToOrder.setAcceptDrops(False)
        self.QTWProductToOrder.setAutoFillBackground(False)
        self.QTWProductToOrder.setStyleSheet("QTableWidget::item{\n"
"background-color: rgb(255, 255, 255);\n"
"border: none;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(40, 42, 48);\n"
"padding: 0;\n"
"margin: 5px;\n"
"margin-top: 0;\n"
"margin-bottom: 10px;\n"
"}")
        self.QTWProductToOrder.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.QTWProductToOrder.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.QTWProductToOrder.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.QTWProductToOrder.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.QTWProductToOrder.setDragEnabled(False)
        self.QTWProductToOrder.setAlternatingRowColors(False)
        self.QTWProductToOrder.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.QTWProductToOrder.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.QTWProductToOrder.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.QTWProductToOrder.setShowGrid(False)
        self.QTWProductToOrder.setGridStyle(QtCore.Qt.NoPen)
        self.QTWProductToOrder.setObjectName("QTWProductToOrder")
        self.QTWProductToOrder.setColumnCount(4)
        self.QTWProductToOrder.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.QTWProductToOrder.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWProductToOrder.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWProductToOrder.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWProductToOrder.setHorizontalHeaderItem(3, item)
        self.QTWProductToOrder.horizontalHeader().setVisible(False)
        self.QTWProductToOrder.horizontalHeader().setCascadingSectionResizes(True)
        self.QTWProductToOrder.horizontalHeader().setDefaultSectionSize(300)
        self.QTWProductToOrder.horizontalHeader().setHighlightSections(True)
        self.QTWProductToOrder.horizontalHeader().setMinimumSectionSize(40)
        self.QTWProductToOrder.horizontalHeader().setSortIndicatorShown(False)
        self.QTWProductToOrder.horizontalHeader().setStretchLastSection(True)
        self.QTWProductToOrder.verticalHeader().setVisible(False)
        self.QTWProductToOrder.verticalHeader().setCascadingSectionResizes(False)
        self.QTWProductToOrder.verticalHeader().setDefaultSectionSize(400)
        self.QTWProductToOrder.verticalHeader().setHighlightSections(True)
        self.QTWProductToOrder.verticalHeader().setMinimumSectionSize(40)
        self.QTWProductToOrder.verticalHeader().setSortIndicatorShown(False)
        self.QTWProductToOrder.verticalHeader().setStretchLastSection(False)
        self.QLESearchProductToOrder = QtWidgets.QLineEdit(self.QWSell)
        self.QLESearchProductToOrder.setGeometry(QtCore.QRect(75, 50, 301, 40))
        self.QLESearchProductToOrder.setMaximumSize(QtCore.QSize(400, 16777215))
        self.QLESearchProductToOrder.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.QLESearchProductToOrder.setStyleSheet("border-radius: 20px;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"")
        self.QLESearchProductToOrder.setObjectName("QLESearchProductToOrder")
        self.QPBCart = QtWidgets.QPushButton(self.QWSell)
        self.QPBCart.setGeometry(QtCore.QRect(1130, 50, 151, 41))
        self.QPBCart.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.QPBCart.setStyleSheet("background-color: rgb(80, 250, 123);\n"
"height: 40px;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 20px;\n"
"padding-left: 25px;\n"
"padding-right: 10px;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/icon/cart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QPBCart.setIcon(icon5)
        self.QPBCart.setIconSize(QtCore.QSize(30, 30))
        self.QPBCart.setObjectName("QPBCart")
        self.QLCountProductToBill = QtWidgets.QLabel(self.QWSell)
        self.QLCountProductToBill.setGeometry(QtCore.QRect(1248, 43, 16, 16))
        self.QLCountProductToBill.setStyleSheet("font: 7pt \"MS Shell Dlg 2\";\n"
"text-align: center;\n"
"background-color: rgb(255, 85, 85);\n"
"color: rgb(248, 248, 242);\n"
"font-weight: bold;\n"
"border-radius: 8px;")
        self.QLCountProductToBill.setScaledContents(True)
        self.QLCountProductToBill.setAlignment(QtCore.Qt.AlignCenter)
        self.QLCountProductToBill.setObjectName("QLCountProductToBill")
        self.QLProductList = QtWidgets.QLabel(self.QWSell)
        self.QLProductList.setGeometry(QtCore.QRect(75, 99, 1206, 51))
        self.QLProductList.setStyleSheet("background-color: rgb(98, 114, 164);\n"
"color: rgb(248, 248, 242);")
        self.QLProductList.setObjectName("QLProductList")
        self.QSW.addWidget(self.QWSell)
        self.QWBillDetails = QtWidgets.QWidget()
        self.QWBillDetails.setObjectName("QWBillDetails")
        self.QTWBillDetails = QtWidgets.QTableWidget(self.QWBillDetails)
        self.QTWBillDetails.setGeometry(QtCore.QRect(70, 70, 1211, 581))
        self.QTWBillDetails.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.QTWBillDetails.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.QTWBillDetails.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.QTWBillDetails.setObjectName("QTWBillDetails")
        self.QTWBillDetails.setColumnCount(6)
        self.QTWBillDetails.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.QTWBillDetails.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWBillDetails.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWBillDetails.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWBillDetails.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWBillDetails.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWBillDetails.setHorizontalHeaderItem(5, item)
        self.QTWBillDetails.horizontalHeader().setVisible(False)
        self.QTWBillDetails.horizontalHeader().setCascadingSectionResizes(True)
        self.QTWBillDetails.horizontalHeader().setHighlightSections(True)
        self.QTWBillDetails.horizontalHeader().setSortIndicatorShown(True)
        self.QTWBillDetails.horizontalHeader().setStretchLastSection(True)
        self.QTWBillDetails.verticalHeader().setVisible(False)
        self.QTWBillDetails.verticalHeader().setCascadingSectionResizes(True)
        self.QTWBillDetails.verticalHeader().setHighlightSections(True)
        self.QTWBillDetails.verticalHeader().setSortIndicatorShown(True)
        self.QTWBillDetails.verticalHeader().setStretchLastSection(False)
        self.QPBPay = QtWidgets.QPushButton(self.QWBillDetails)
        self.QPBPay.setGeometry(QtCore.QRect(1110, 760, 171, 41))
        self.QPBPay.setStyleSheet("background-color: rgb(80, 250, 123);\n"
"height: 40px;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 20px;\n"
"padding-left: 25px;\n"
"padding-right: 10px;")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/icon/pay.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QPBPay.setIcon(icon6)
        self.QPBPay.setIconSize(QtCore.QSize(25, 25))
        self.QPBPay.setObjectName("QPBPay")
        self.QLTotalPrice = QtWidgets.QLabel(self.QWBillDetails)
        self.QLTotalPrice.setGeometry(QtCore.QRect(960, 680, 121, 41))
        self.QLTotalPrice.setObjectName("QLTotalPrice")
        self.QLTotalPriceNumeric = QtWidgets.QLabel(self.QWBillDetails)
        self.QLTotalPriceNumeric.setGeometry(QtCore.QRect(1090, 680, 191, 41))
        self.QLTotalPriceNumeric.setText("")
        self.QLTotalPriceNumeric.setObjectName("QLTotalPriceNumeric")
        self.QSW.addWidget(self.QWBillDetails)
        self.QWStaticstics = QtWidgets.QWidget()
        self.QWStaticstics.setObjectName("QWStaticstics")
        self.QTWStaticstics = QtWidgets.QTableWidget(self.QWStaticstics)
        self.QTWStaticstics.setGeometry(QtCore.QRect(40, 100, 1271, 701))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.QTWStaticstics.setFont(font)
        self.QTWStaticstics.setMouseTracking(False)
        self.QTWStaticstics.setTabletTracking(False)
        self.QTWStaticstics.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.QTWStaticstics.setAcceptDrops(False)
        self.QTWStaticstics.setAutoFillBackground(False)
        self.QTWStaticstics.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.QTWStaticstics.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.QTWStaticstics.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.QTWStaticstics.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.QTWStaticstics.setDragEnabled(False)
        self.QTWStaticstics.setAlternatingRowColors(False)
        self.QTWStaticstics.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.QTWStaticstics.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.QTWStaticstics.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.QTWStaticstics.setShowGrid(False)
        self.QTWStaticstics.setGridStyle(QtCore.Qt.NoPen)
        self.QTWStaticstics.setObjectName("QTWStaticstics")
        self.QTWStaticstics.setColumnCount(6)
        self.QTWStaticstics.setRowCount(19)
        item = QtWidgets.QTableWidgetItem()
        self.QTWStaticstics.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWStaticstics.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWStaticstics.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWStaticstics.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWStaticstics.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWStaticstics.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWStaticstics.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWStaticstics.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWStaticstics.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWStaticstics.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWStaticstics.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWStaticstics.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWStaticstics.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWStaticstics.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWStaticstics.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWStaticstics.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWStaticstics.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWStaticstics.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWStaticstics.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWStaticstics.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWStaticstics.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWStaticstics.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWStaticstics.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWStaticstics.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.QTWStaticstics.setHorizontalHeaderItem(5, item)
        self.QTWStaticstics.horizontalHeader().setVisible(False)
        self.QTWStaticstics.horizontalHeader().setCascadingSectionResizes(True)
        self.QTWStaticstics.horizontalHeader().setDefaultSectionSize(200)
        self.QTWStaticstics.horizontalHeader().setHighlightSections(True)
        self.QTWStaticstics.horizontalHeader().setMinimumSectionSize(40)
        self.QTWStaticstics.horizontalHeader().setSortIndicatorShown(False)
        self.QTWStaticstics.horizontalHeader().setStretchLastSection(True)
        self.QTWStaticstics.verticalHeader().setVisible(False)
        self.QTWStaticstics.verticalHeader().setCascadingSectionResizes(False)
        self.QTWStaticstics.verticalHeader().setDefaultSectionSize(40)
        self.QTWStaticstics.verticalHeader().setHighlightSections(True)
        self.QTWStaticstics.verticalHeader().setMinimumSectionSize(40)
        self.QTWStaticstics.verticalHeader().setSortIndicatorShown(False)
        self.QTWStaticstics.verticalHeader().setStretchLastSection(False)
        self.QSW.addWidget(self.QWStaticstics)

        self.retranslateUi(Program)
        self.QSW.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Program)
        Program.setTabOrder(self.QPBProduct, self.QPBSell)

    def retranslateUi(self, Program):
        _translate = QtCore.QCoreApplication.translate
        Program.setWindowTitle(_translate("Program", "Form"))
        self.QPBProduct.setText(_translate("Program", " Sản phẩm"))
        self.QPBSell.setText(_translate("Program", " Bán hàng"))
        self.QPBStatistics.setText(_translate("Program", " Thống kê"))
        self.QPBExit.setText(_translate("Program", " Thoát"))
        self.QLTitle.setText(_translate("Program", "<html><head/><body><p><br/></p></body></html>"))
        self.QTWProduct.setSortingEnabled(False)
        item = self.QTWProduct.horizontalHeaderItem(0)
        item.setText(_translate("Program", "Ảnh"))
        item = self.QTWProduct.horizontalHeaderItem(1)
        item.setText(_translate("Program", "Mã sữa"))
        item = self.QTWProduct.horizontalHeaderItem(2)
        item.setText(_translate("Program", "Tên sữa"))
        item = self.QTWProduct.horizontalHeaderItem(3)
        item.setText(_translate("Program", "Tên công ty sản xuất"))
        item = self.QTWProduct.horizontalHeaderItem(4)
        item.setText(_translate("Program", "Quy cách hàng hóa"))
        item = self.QTWProduct.horizontalHeaderItem(5)
        item.setText(_translate("Program", "Đơn giá"))
        item = self.QTWProduct.horizontalHeaderItem(6)
        item.setText(_translate("Program", "Số lượng"))
        item = self.QTWProduct.horizontalHeaderItem(7)
        item.setText(_translate("Program", "Hành động"))
        self.QLESearchProduct.setPlaceholderText(_translate("Program", "Nhập mã hoặc tên để tìm kiếm"))
        self.QPBAddProduct.setText(_translate("Program", "Thêm"))
        self.QTWProductToOrder.setSortingEnabled(False)
        self.QLESearchProductToOrder.setPlaceholderText(_translate("Program", "Nhập mã hoặc tên để tìm kiếm"))
        self.QPBCart.setText(_translate("Program", "Giỏ hàng"))
        self.QLCountProductToBill.setText(_translate("Program", "<html><head/><body><p align=\"center\"><span style=\" font-size:6pt;\">1</span></p></body></html>"))
        self.QLProductList.setText(_translate("Program", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Danh sách sản phẩm</span></p></body></html>"))
        item = self.QTWBillDetails.horizontalHeaderItem(0)
        item.setText(_translate("Program", "Ảnh"))
        item = self.QTWBillDetails.horizontalHeaderItem(1)
        item.setText(_translate("Program", "Tên sữa"))
        item = self.QTWBillDetails.horizontalHeaderItem(2)
        item.setText(_translate("Program", "Số lượng"))
        item = self.QTWBillDetails.horizontalHeaderItem(3)
        item.setText(_translate("Program", "Đơn giá"))
        item = self.QTWBillDetails.horizontalHeaderItem(4)
        item.setText(_translate("Program", "Thành tiền"))
        item = self.QTWBillDetails.horizontalHeaderItem(5)
        item.setText(_translate("Program", "Xóa"))
        self.QPBPay.setText(_translate("Program", "Thanh toán"))
        self.QLTotalPrice.setText(_translate("Program", "<html><head/><body><p><span style=\" font-weight:600;\">Thành tiền:</span></p></body></html>"))
        self.QTWStaticstics.setSortingEnabled(False)
        item = self.QTWStaticstics.verticalHeaderItem(0)
        item.setText(_translate("Program", "New Row"))
        item = self.QTWStaticstics.verticalHeaderItem(1)
        item.setText(_translate("Program", "New Row"))
        item = self.QTWStaticstics.verticalHeaderItem(2)
        item.setText(_translate("Program", "New Row"))
        item = self.QTWStaticstics.verticalHeaderItem(3)
        item.setText(_translate("Program", "New Row"))
        item = self.QTWStaticstics.verticalHeaderItem(4)
        item.setText(_translate("Program", "New Row"))
        item = self.QTWStaticstics.verticalHeaderItem(5)
        item.setText(_translate("Program", "New Row"))
        item = self.QTWStaticstics.verticalHeaderItem(6)
        item.setText(_translate("Program", "New Row"))
        item = self.QTWStaticstics.verticalHeaderItem(7)
        item.setText(_translate("Program", "New Row"))
        item = self.QTWStaticstics.verticalHeaderItem(8)
        item.setText(_translate("Program", "New Row"))
        item = self.QTWStaticstics.verticalHeaderItem(9)
        item.setText(_translate("Program", "New Row"))
        item = self.QTWStaticstics.verticalHeaderItem(10)
        item.setText(_translate("Program", "New Row"))
        item = self.QTWStaticstics.verticalHeaderItem(11)
        item.setText(_translate("Program", "New Row"))
        item = self.QTWStaticstics.verticalHeaderItem(12)
        item.setText(_translate("Program", "New Row"))
        item = self.QTWStaticstics.verticalHeaderItem(13)
        item.setText(_translate("Program", "New Row"))
        item = self.QTWStaticstics.verticalHeaderItem(14)
        item.setText(_translate("Program", "New Row"))
        item = self.QTWStaticstics.verticalHeaderItem(15)
        item.setText(_translate("Program", "New Row"))
        item = self.QTWStaticstics.verticalHeaderItem(16)
        item.setText(_translate("Program", "New Row"))
        item = self.QTWStaticstics.verticalHeaderItem(17)
        item.setText(_translate("Program", "New Row"))
        item = self.QTWStaticstics.verticalHeaderItem(18)
        item.setText(_translate("Program", "New Row"))
        item = self.QTWStaticstics.horizontalHeaderItem(0)
        item.setText(_translate("Program", "Mã sữa"))
        item = self.QTWStaticstics.horizontalHeaderItem(1)
        item.setText(_translate("Program", "Tên sữa"))
        item = self.QTWStaticstics.horizontalHeaderItem(2)
        item.setText(_translate("Program", "Tên công ty sản xuất"))
        item = self.QTWStaticstics.horizontalHeaderItem(3)
        item.setText(_translate("Program", "Quy cách hàng hóa"))
        item = self.QTWStaticstics.horizontalHeaderItem(4)
        item.setText(_translate("Program", "Đơn giá"))
        item = self.QTWStaticstics.horizontalHeaderItem(5)
        item.setText(_translate("Program", "Số lượng tồn kho"))
import src_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Program = QtWidgets.QWidget()
    ui = Ui_Program()
    ui.setupUi(Program)
    Program.show()
    sys.exit(app.exec_())
