        self.uic.QTWProduct.setColumnWidth(0, 100)
        self.uic.QTWProduct.setColumnWidth(1, 100)
        self.uic.QTWProduct.setColumnWidth(2, 250)
        self.uic.QTWProduct.setColumnWidth(3, 250)
        self.uic.QTWProduct.setColumnWidth(4, 250)
        self.uic.QTWProduct.setColumnWidth(5, 100)
        self.uic.QTWProduct.setColumnWidth(6, 100)